ICON_SIZE = 48
ORIGINAL_ICON_SIZE = 48
CONTAINER_WIDTH = 96
CONTAINER_HEIGHT = 120

CONTAINER_MARGIN_TOP = 15
CONTAINER_MARGIN_BOTTOM = 0
CONTAINER_MARGIN_LEFT = 5
CONTAINER_MARGIN_RIGHT = 5

ACTION_FONT_SIZE = 12
CATEGORY_FONT_SIZE = 10

SPACING = 10